@gatewayUrl = http://localhost:5000
@aggregatorUrl = http://localhost:5010
@notifierUrl = http://localhost:5020
@newsFeedUrl = http://localhost:5030
@quotesFeedUrl = http://localhost:5090
@weatherFeedUrl = http://localhost:5050

###
POST {{gatewayUrl}}/feeds/quotes/pricing/start

###
GET {{aggregatorUrl}}

###
GET {{notifierUrl}}

###
GET {{newsFeedUrl}}

###
GET {{quotesFeedUrl}}

###
POST {{quotesFeedUrl}}/pricing/start

###
POST {{quotesFeedUrl}}/pricing/stop

###
GET {{weatherFeedUrl}}
